files = bytes_in_file.c calc_checksum.c calcn_checksum.c create_checksum_file.c create_fail_file.c extract_checksum.c
all:
	gcc checksum1.c $(files) -o mychecksum1
	gcc checksum2.c $(files) -o mychecksum2
clean:
	rm -rf mychecksum1
	rm -rf mychecksum2
